export const DEMO_NEWS = [
  {
    id: "news-roadshow-kit",
    title: "เปิดชุด Exercise ใหม่สำหรับกิจกรรม Roadshow",
    summary: "ทีม Creator เพิ่ม Exercise ที่รวมไฟล์ Drive และควิซไว้กับคลิปเดียวกันแล้ว",
    body:
      "ตอนนี้นักเรียนสามารถเข้าแท็บ Exercise ในแต่ละวิชาเพื่อเปิดไฟล์ worksheet จาก Drive และทำควิซที่ผูกกับคลิปนั้นได้ในที่เดียว เหมาะสำหรับใช้หลังดูคลิปหรือระหว่างกิจกรรมในห้องเรียน",
    imageUrl: "",
    audience: "all",
    priority: "high",
    status: "published",
    actionLabel: "ไปดู Exercise",
    actionUrl: "/subject/biology?type=exercise",
    publishedAt: "2026-06-24T00:00:00.000Z",
    createdAt: "2026-06-24T00:00:00.000Z",
  },
  {
    id: "news-giveaway-unseen",
    title: "Give Away&Unseen เปิดให้นักเรียนล็อกอินเพื่อรับไฟล์",
    summary: "ไฟล์แจกและ unseen material จะเปิดได้หลังเข้าสู่ระบบเท่านั้น",
    body:
      "เพื่อให้ทีมติดตามการใช้งานและป้องกันลิงก์หลุดนอกระบบ ปุ่มเปิดไฟล์และ Google Drive ใน Give Away&Unseen จะพาไปหน้าเข้าสู่ระบบก่อน นักเรียนที่ล็อกอินแล้วสามารถเปิดไฟล์ได้ตามปกติ",
    imageUrl: "",
    audience: "student",
    priority: "normal",
    status: "published",
    actionLabel: "ดู Give Away&Unseen",
    actionUrl: "/subject/physics?type=file",
    publishedAt: "2026-06-23T00:00:00.000Z",
    createdAt: "2026-06-23T00:00:00.000Z",
  },
];

export const DEMO_QUIZZES = [
  {
    id: "demo-osmosis",
    title: "Cell Balance: Osmosis Quick Check",
    description: "ควิซสั้นจากแนว roadshow ชีววิทยา เรื่องน้ำ เกลือ และสมดุลของเซลล์",
    subject: "biology",
    contentId: "clip-biology-osmosis",
    status: "published",
    createdAt: "2026-06-21T00:00:00.000Z",
    questions: [
      {
        id: "bio-q1",
        prompt: "ถ้าเซลล์อยู่ในสารละลายที่มีความเข้มข้นของเกลือสูงกว่าภายในเซลล์ น้ำมีแนวโน้มเคลื่อนที่อย่างไร",
        type: "multiple_choice",
        points: 1,
        explanation: "น้ำจะเคลื่อนออกจากเซลล์ไปยังบริเวณที่มีความเข้มข้นของสารละลายสูงกว่า",
        order: 0,
        choices: [
          { id: "bio-q1-a", label: "น้ำเคลื่อนออกจากเซลล์", isCorrect: true, order: 0 },
          { id: "bio-q1-b", label: "น้ำเคลื่อนเข้าเซลล์", isCorrect: false, order: 1 },
          { id: "bio-q1-c", label: "เกลือเคลื่อนออกจากเซลล์ทั้งหมด", isCorrect: false, order: 2 },
        ],
      },
      {
        id: "bio-q2",
        prompt: "ในเกม Cell Balance การใช้พลังงาน ATP สื่อถึงอะไร",
        type: "multiple_choice",
        points: 1,
        explanation: "ATP แทนพลังงานที่เซลล์ใช้เพื่อควบคุมสมดุล ไม่ใช่การเคลื่อนที่อัตโนมัติ",
        order: 1,
        choices: [
          { id: "bio-q2-a", label: "การแก้สมดุลแบบใช้พลังงาน", isCorrect: true, order: 0 },
          { id: "bio-q2-b", label: "การเปลี่ยนเกลือให้เป็นน้ำ", isCorrect: false, order: 1 },
          { id: "bio-q2-c", label: "แรงโน้มถ่วงในเซลล์", isCorrect: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "demo-physics-car",
    title: "Rubber Band Car: Energy and Motion",
    description: "เช็กความเข้าใจเรื่องพลังงานสะสม แรงเสียดทาน และการเคลื่อนที่",
    subject: "physics",
    status: "published",
    createdAt: "2026-06-21T00:00:00.000Z",
    questions: [
      {
        id: "phy-q1",
        prompt: "การบิดยางรัดในรถพลังยางทำหน้าที่หลักอะไร",
        type: "multiple_choice",
        points: 1,
        explanation: "ยางที่ถูกบิดเก็บพลังงานศักย์ยืดหยุ่น แล้วเปลี่ยนเป็นพลังงานจลน์เมื่อปล่อย",
        order: 0,
        choices: [
          { id: "phy-q1-a", label: "เก็บพลังงานศักย์ยืดหยุ่น", isCorrect: true, order: 0 },
          { id: "phy-q1-b", label: "ลดมวลของรถ", isCorrect: false, order: 1 },
          { id: "phy-q1-c", label: "ทำให้แรงเสียดทานหายไป", isCorrect: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "demo-chem-factory",
    title: "Separation Factory: Tools and Properties",
    description: "เลือกเครื่องมือแยกสารให้ตรงกับสมบัติของสารผสม",
    subject: "chemistry",
    status: "published",
    createdAt: "2026-06-21T00:00:00.000Z",
    questions: [
      {
        id: "chem-q1",
        prompt: "ถ้าต้องแยกเศษเหล็กออกจากทราย เครื่องมือใดเหมาะที่สุด",
        type: "multiple_choice",
        points: 1,
        explanation: "แม่เหล็กใช้แยกสารที่มีสมบัติแม่เหล็กออกจากสารที่ไม่มีสมบัตินั้น",
        order: 0,
        choices: [
          { id: "chem-q1-a", label: "แม่เหล็ก", isCorrect: true, order: 0 },
          { id: "chem-q1-b", label: "กระดาษกรอง", isCorrect: false, order: 1 },
          { id: "chem-q1-c", label: "การระเหยน้ำ", isCorrect: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "demo-growth",
    title: "Growth Race: Linear vs Exponential",
    description: "ฝึกแยกโครงสร้างการเติบโตแบบบวกคงที่และคูณคงที่",
    subject: "math",
    status: "published",
    createdAt: "2026-06-21T00:00:00.000Z",
    questions: [
      {
        id: "math-q1",
        prompt: "ลำดับ 2, 4, 8, 16 เป็นการเติบโตแบบใด",
        type: "multiple_choice",
        points: 1,
        explanation: "แต่ละพจน์คูณ 2 จากพจน์ก่อนหน้า จึงเป็น exponential growth",
        order: 0,
        choices: [
          { id: "math-q1-a", label: "Exponential growth", isCorrect: true, order: 0 },
          { id: "math-q1-b", label: "Linear growth", isCorrect: false, order: 1 },
          { id: "math-q1-c", label: "ไม่มีรูปแบบ", isCorrect: false, order: 2 },
        ],
      },
    ],
  },
];

export const DEMO_CONTENT = [
  {
    id: "clip-biology-osmosis",
    type: "clip",
    title: "Osmosis in 90 Seconds",
    description: "ดูภาพรวมการเคลื่อนที่ของน้ำผ่านเยื่อเลือกผ่าน ก่อนลองควิซ Cell Balance",
    subject: "biology",
    url: "https://www.youtube.com/watch?v=aircAruvnKk",
    thumbnailUrl: "https://i.ytimg.com/vi/aircAruvnKk/hqdefault.jpg",
    resourceFileName: "osmosis-quick-notes.txt",
    resourceFileUrl: "data:text/plain;charset=utf-8,Osmosis%20Quick%20Notes%0A1.%20Water%20moves%20across%20a%20selectively%20permeable%20membrane.%0A2.%20Compare%20solute%20concentration%20inside%20and%20outside%20the%20cell.",
    status: "published",
    createdAt: "2026-06-21T00:00:00.000Z",
  },
  {
    id: "clip-physics-method",
    type: "clip",
    title: "วิธีคิดโจทย์พลังงานจาก Rubber Band Car",
    description: "คลิปสั้นที่พาแยกตัวแปร พลังงานสะสม แรงเสียดทาน และการทดลองซ้ำ",
    subject: "physics",
    url: "https://www.youtube.com/watch?v=aircAruvnKk",
    thumbnailUrl: "https://i.ytimg.com/vi/aircAruvnKk/hqdefault.jpg",
    status: "published",
    createdAt: "2026-06-21T00:00:00.000Z",
  },
  {
    id: "file-physics-giveaway",
    type: "file",
    title: "Rubber Band Car Giveaway Sheet",
    description: "worksheet และของแจกสำหรับกิจกรรมรถพลังยาง นักเรียนเปิดได้จากแท็บ Give Away&Unseen โดยไม่ต้องเข้าไปในคลิป",
    subject: "physics",
    url: "",
    thumbnailUrl: "/assets/kvisdom-roadshow-class.jpg",
    thumbnailPositionX: 50,
    thumbnailPositionY: 50,
    detailText:
      "ไฟล์นี้เป็น worksheet สั้นสำหรับใช้หลังหรือระหว่างกิจกรรม Rubber Band Car นักเรียนจะได้ร่างแบบรถ บันทึกจำนวนรอบที่หมุนยาง ระยะทางที่รถเคลื่อนที่ และเขียนข้อเสนอเพื่อปรับปรุงรอบทดลองถัดไป เหมาะสำหรับใช้เป็นใบงานในห้องเรียนหรือเป็นของแจกหลัง roadshow เพื่อให้นักเรียนกลับไปทดลองต่อเองได้",
    resourceFileName: "rubber-band-car-giveaway.txt",
    resourceFileUrl:
      "data:text/plain;charset=utf-8,Rubber%20Band%20Car%20Giveaway%20Sheet%0A1.%20Sketch%20your%20car%20design.%0A2.%20Record%20rubber%20band%20turns%20and%20distance.%0A3.%20Write%20one%20improvement%20for%20the%20next%20trial.",
    status: "published",
    createdAt: "2026-06-21T00:00:00.000Z",
  },
  {
    id: "clip-growth-race",
    type: "clip",
    title: "Linear vs Exponential Growth Race",
    description: "ดูโครงสร้างการเติบโตจากเกมคณิตศาสตร์ แล้วค่อยไปลองทำควิซ",
    subject: "math",
    url: "https://www.youtube.com/watch?v=aircAruvnKk",
    thumbnailUrl: "https://i.ytimg.com/vi/aircAruvnKk/hqdefault.jpg",
    status: "published",
    createdAt: "2026-06-21T00:00:00.000Z",
  },
  {
    id: "fact-physics-friction",
    type: "fact",
    title: "แรงเสียดทานไม่ได้เป็นศัตรูเสมอไป",
    description: "ในรถพลังยาง แรงเสียดทานบางส่วนทำให้ล้อเกาะพื้นและเปลี่ยนพลังงานเป็นการเคลื่อนที่ได้",
    subject: "physics",
    url: "https://drive.google.com/file/d/1physicsKvisdomDemoPreview/view?usp=sharing",
    thumbnailUrl: "/assets/kvisdom-roadshow-class.jpg",
    thumbnailPositionX: 50,
    thumbnailPositionY: 45,
    detailText:
      "แรงเสียดทานไม่ได้มีหน้าที่แค่ทำให้วัตถุช้าลง ในบางสถานการณ์แรงเสียดทานคือแรงที่ช่วยให้เกิดการเคลื่อนที่จริง เช่น ล้อรถต้องเกาะพื้นก่อนจึงจะผลักรถไปข้างหน้าได้ ถ้าแรงเสียดทานน้อยเกินไป ล้อจะหมุนฟรีและพลังงานจากยางรัดจะไม่ถูกส่งต่อเป็นการเคลื่อนที่อย่างมีประสิทธิภาพ",
    status: "published",
    createdAt: "2026-06-21T00:00:00.000Z",
  },
  {
    id: "clip-chem-separation",
    type: "clip",
    title: "Separation Tools Walkthrough",
    description: "พาเลือกแม่เหล็ก การกรอง การระเหย และโครมาโทกราฟีจากสมบัติของสาร",
    subject: "chemistry",
    url: "https://www.youtube.com/watch?v=aircAruvnKk",
    thumbnailUrl: "https://i.ytimg.com/vi/aircAruvnKk/hqdefault.jpg",
    status: "published",
    createdAt: "2026-06-21T00:00:00.000Z",
  },
  {
    id: "fact-osmosis",
    type: "fact",
    title: "ทำไมมันฝรั่งเปลี่ยนเนื้อสัมผัสในน้ำเกลือ",
    description: "เกร็ดวิทย์จาก osmosis ที่โยงจากการทดลองง่าย ๆ ไปสู่การทำงานของเซลล์",
    subject: "biology",
    url: "https://drive.google.com/file/d/1biologyKvisdomDemoPreview/view?usp=sharing",
    thumbnailUrl: "/assets/kvisdom-roadshow-class.jpg",
    thumbnailPositionX: 50,
    thumbnailPositionY: 45,
    detailText:
      "Osmosis คือการเคลื่อนที่ของน้ำผ่านเยื่อเลือกผ่านจากบริเวณที่มีความเข้มข้นของสารละลายต่ำกว่าไปยังบริเวณที่มีความเข้มข้นสูงกว่า ตัวอย่างมันฝรั่งในน้ำเกลือช่วยให้เห็นว่าเซลล์สูญเสียน้ำได้อย่างไร ซึ่งเชื่อมโยงกับการรักษาสมดุลน้ำในสิ่งมีชีวิต",
    status: "published",
    createdAt: "2026-06-21T00:00:00.000Z",
  },
  {
    id: "fact-growth",
    type: "fact",
    title: "ทำไม exponential ถึงโตไวเกินคาด",
    description: "เมื่อจำนวนเพิ่มแบบคูณ ผลต่างช่วงหลังจะใหญ่กว่าช่วงแรกมาก แม้กฎจะดูเรียบง่าย",
    subject: "math",
    url: "https://drive.google.com/file/d/1mathKvisdomDemoPreview/view?usp=sharing",
    thumbnailUrl: "/assets/kvisdom-roadshow-class.jpg",
    thumbnailPositionX: 50,
    thumbnailPositionY: 45,
    detailText:
      "การเติบโตแบบ exponential เกิดขึ้นเมื่อปริมาณเพิ่มขึ้นเป็นสัดส่วนกับค่าปัจจุบันของมันเอง ช่วงแรกอาจดูไม่ต่างจาก linear มากนัก แต่เมื่อเวลาผ่านไป ฐานที่ใหญ่ขึ้นทำให้การเพิ่มในแต่ละรอบพุ่งเร็วขึ้นมาก นี่คือเหตุผลที่กราฟแบบนี้พบได้ทั้งในประชากร ดอกเบี้ยทบต้น และการแพร่กระจายของข้อมูล",
    status: "published",
    createdAt: "2026-06-21T00:00:00.000Z",
  },
];
